use std::{
    fs,
    path::{Path, PathBuf},
    str::FromStr,
};

use anyhow::{Context, Result};

use crate::{
    module::ModuleConfig,
    version::Version,
};

/// For each module, look at `src/<rocmrc_name>/sys/linked/sys_*.rs` and write
/// `src/<rocmrc_name>/sys/sys.rs` as a list of cfg-gated `include!`s.
///
/// Single-version case: a single unconditional `include!`.
pub fn merge_bindings(modules: &[ModuleConfig]) -> Result<()> {
    let root = crate_root();
    for m in modules {
        let module_sys = root.join("src").join(m.rocmrc_name).join("sys");
        let linked_dir = module_sys.join("linked");
        if !linked_dir.exists() {
            log::warn!(
                "skipping merge for {}: no linked/ directory at {}",
                m.rocmrc_name,
                linked_dir.display()
            );
            continue;
        }

        let mut versions = collect_versions(&linked_dir)
            .with_context(|| format!("scanning {}", linked_dir.display()))?;
        if versions.is_empty() {
            log::warn!(
                "skipping merge for {}: no sys_*.rs files in {}",
                m.rocmrc_name,
                linked_dir.display()
            );
            continue;
        }
        versions.sort();

        let out = module_sys.join("sys.rs");
        let body = render(&versions, m.feature_prefix);
        fs::write(&out, body).with_context(|| format!("writing {}", out.display()))?;
        log::info!("merged {} -> {}", m.rocmrc_name, out.display());
    }
    Ok(())
}

fn collect_versions(linked_dir: &Path) -> Result<Vec<Version>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(linked_dir)? {
        let entry = entry?;
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        let Some(rest) = name.strip_prefix("sys_") else { continue };
        let Some(ver) = rest.strip_suffix(".rs") else { continue };
        match Version::from_str(ver) {
            Ok(v) => out.push(v),
            Err(e) => log::warn!("ignoring {}: {e}", name),
        }
    }
    Ok(out)
}

fn render(versions: &[Version], feature_prefix: &str) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by bindings_generator. Do not edit by hand.\n");
    if versions.len() == 1 {
        let v = versions[0];
        s.push_str(&format!("include!(\"linked/sys_{v}.rs\");\n"));
    } else {
        for v in versions {
            let feat = v.feature_name(feature_prefix);
            s.push_str(&format!(
                "#[cfg(feature = \"{feat}\")]\ninclude!(\"linked/sys_{v}.rs\");\n"
            ));
        }
    }
    s
}

fn crate_root() -> PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .parent()
        .expect("bindings_generator manifest must have a parent")
        .to_path_buf()
}
